/**
 * app/[locale]/tools/[slug]/page.tsx
 *
 * Localized tool page for the 10 pilot tools in Phase 2:
 * /es/tools/[slug], /de/tools/[slug], /fr/tools/[slug], /pt/tools/[slug], /ja/tools/[slug]
 *
 * Requirements:
 *  - Only the 10 pilot tools resolve (return 200).
 *  - Any unsupported tool (e.g. /es/tools/401k-calculator) returns 404.
 *  - Any unsupported locale (e.g. /it/tools/bmi-calculator) returns 404.
 *  - All localized pages have robots: { index: false, follow: true } (noindex).
 *  - No hreflang tags added in Phase 2.
 *  - Sitemap contains 0 localized URLs.
 *  - Uses existing React calculator components from toolsRegistry without touching business logic.
 */

import React from 'react';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Metadata } from 'next';
import { getDbData } from '@/lib/db';
import { toolsRegistry } from '@/components/tools/registry';
import RelatedTools from '@/components/RelatedTools';
import FAQ from '@/components/FAQ';
import ShareButtons from '@/components/ShareButtons';
import AdBanner from '@/components/AdBanner';
import { ChevronRight, Home } from 'lucide-react';
import EmbedWidgetBox from '@/components/EmbedWidgetBox';

import {
  isValidLocale,
  getLocaleConfig,
  DEFAULT_LOCALE,
  NON_DEFAULT_LOCALES,
  PILOT_TOOLS,
  isPilotTool,
  getHreflangMap,
  Locale,
} from '@/lib/i18n';
import { loadTranslations, t } from '@/lib/translations';
import { getToolTranslation } from '@/lib/pilot-translations';

interface LocaleToolPageProps {
  params: Promise<{ locale: string; slug: string }> | { locale: string; slug: string };
  searchParams?: Promise<{ [key: string]: string | string[] | undefined }> | { [key: string]: string | string[] | undefined };
}

/**
 * dynamicParams = false ensures any route not generated by generateStaticParams (e.g. non-pilot tools)
 * automatically returns HTTP 404!
 */
export const dynamicParams = false;

export async function generateStaticParams(): Promise<{ locale: string; slug: string }[]> {
  const params: { locale: string; slug: string }[] = [];

  for (const locale of NON_DEFAULT_LOCALES) {
    for (const slug of PILOT_TOOLS) {
      params.push({ locale, slug });
    }
  }

  return params;
}

export async function generateMetadata(props: LocaleToolPageProps): Promise<Metadata> {
  const resolvedParams = await props.params;
  const { locale, slug } = resolvedParams;

  if (!isValidLocale(locale) || locale === DEFAULT_LOCALE || !isPilotTool(slug)) {
    return {
      title: 'Tool Not Found - HelloTools',
    };
  }

  const config = getLocaleConfig(locale as Locale);
  const content = getToolTranslation(slug, locale as Locale);
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://hellotools.net';
  const hreflangLanguages = getHreflangMap(slug);

  const rawLocaleTitle = content.seoTitle || `${content.name} — ${config.nativeName} | HelloTools`;
  // Strip trailing '| HelloTools' so layout title.template doesn't produce a double suffix
  const cleanLocaleTitle = rawLocaleTitle.replace(/\s*\|\s*HelloTools\s*$/i, '');

  return {
    title: cleanLocaleTitle,
    description: content.seoDescription || content.description,
    alternates: {
      canonical: `${baseUrl}/${locale}/tools/${slug}`,
      ...(hreflangLanguages ? { languages: hreflangLanguages } : {}),
    },
    openGraph: {
      title: content.seoTitle || content.name,
      description: content.seoDescription || content.description,
      url: `${baseUrl}/${locale}/tools/${slug}`,
      type: 'website',
      siteName: 'HelloTools',
      locale: config.intlCode,
      images: [
        {
          url: `${baseUrl}/og-image.png`,
          width: 1200,
          height: 630,
          alt: content.name,
        },
      ],
    },
    robots: {
      index: config.indexable, // true for Spanish (es), false for de, fr, pt, ja
      follow: true,
    },
  };
}

export default async function LocaleToolPage(props: LocaleToolPageProps) {
  const resolvedParams = await props.params;
  const resolvedSearchParams = props.searchParams ? await props.searchParams : {};
  const { locale, slug } = resolvedParams;

  // Guard: invalid locale or non-pilot tool → 404
  if (!isValidLocale(locale) || locale === DEFAULT_LOCALE || !isPilotTool(slug)) {
    notFound();
  }

  const isEmbed = resolvedSearchParams.embed === 'true';
  const ToolComponent = toolsRegistry[slug];

  if (!ToolComponent) {
    notFound();
  }

  const currentLocale = locale as Locale;
  const config = getLocaleConfig(currentLocale);
  const content = getToolTranslation(slug, currentLocale);
  const common = loadTranslations(currentLocale);
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://hellotools.net';

  // Find tool metadata from master for category info
  const dbData = getDbData();
  const masterTool = dbData.tools.find((t) => t.slug === slug);
  const categoryKey = masterTool?.category || 'utility';

  // Localized category name
  const categoryName = t(common, `categories.${categoryKey}`) || categoryKey;

  if (isEmbed) {
    return (
      <div className="p-4 bg-transparent">
        <style
          dangerouslySetInnerHTML={{
            __html: `
          header, footer { display: none !important; }
          body { background: transparent !important; }
          main { padding: 0 !important; }
        `,
          }}
        />
        <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-6 shadow-sm max-w-2xl mx-auto animate-fade-in">
          <div className="mb-4">
            <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-1.5 justify-center">
              <span>{content.name}</span>
            </h3>
          </div>
          <ToolComponent />
          <div className="mt-4 text-center">
            <a
              href={`${baseUrl}/${locale}/tools/${slug}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[10px] text-gray-400 hover:text-blue-500 hover:underline transition-colors font-medium"
            >
              Powered by HelloTools ({config.nativeName})
            </a>
          </div>
        </div>
      </div>
    );
  }

  const faqsToUse = content.faqs && content.faqs.length > 0 ? content.faqs : [];

  // Construct JSON-LD Schema structures
  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: t(common, 'nav.home'),
        item: `${baseUrl}/${locale}`,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: categoryName,
        item: `${baseUrl}/${locale}/#${categoryKey}`,
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: content.name,
        item: `${baseUrl}/${locale}/tools/${slug}`,
      },
    ],
  };

  const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: content.name,
    url: `${baseUrl}/${locale}/tools/${slug}`,
    description: content.seoDescription || content.description,
    applicationCategory: ({ finance: 'FinanceApplication', health: 'HealthApplication', math: 'EducationalApplication', text: 'UtilitiesApplication', utility: 'UtilitiesApplication' })[masterTool?.category || ''] || 'UtilitiesApplication',
    operatingSystem: 'Any',
    'offers': {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqsToUse.map((faq) => ({
      '@type': 'Question',
      name: faq.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.a,
      },
    })),
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Schema Markup Injection */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
      />
      {faqsToUse.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      )}

      {/* Breadcrumbs */}
      <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400 mb-6 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800/80 px-4 py-2.5 rounded-xl">
        <Link href={`/${locale}`} className="hover:text-gray-950 dark:hover:text-white flex items-center gap-1">
          <Home className="h-3.5 w-3.5" />
          <span>{t(common, 'nav.home')}</span>
        </Link>
        <ChevronRight className="h-3 w-3" />
        <Link href={`/${locale}/#${categoryKey}`} className="hover:text-gray-950 dark:hover:text-white">
          {categoryName}
        </Link>
        <ChevronRight className="h-3 w-3" />
        <span className="text-[#f97316] dark:text-blue-400 font-bold truncate">{content.name}</span>
      </nav>

      {/* Top Advertisement Banner */}
      <AdBanner
        adCode={process.env.NEXT_PUBLIC_ADSTERRA_BANNER_1 || ''}
        width={728}
        height={90}
      />

      {/* Page Header */}
      <div className="mb-6">
        <h1 className="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white bg-gradient-to-r from-gray-900 to-gray-700 dark:from-white dark:to-blue-100 bg-clip-text text-transparent inline-block">
          {content.name}
        </h1>
        <p className="mt-2 text-sm text-slate-600 dark:text-blue-200/80 leading-relaxed max-w-3xl">
          {content.description}
        </p>
      </div>

      {/* Overview Summary Box */}
      {content.quickAnswer && (
        <div className="mb-8 p-4 rounded-xl bg-orange-50/50 dark:bg-blue-950/20 border border-orange-200/50 dark:border-blue-900/30 text-slate-700 dark:text-blue-200 text-sm leading-relaxed flex items-start gap-2">
          <span className="font-bold text-[#f97316] dark:text-blue-400 shrink-0">
            {t(common, 'tool.summary')}:
          </span>
          <span>{content.quickAnswer}</span>
        </div>
      )}

      {/* Main Panel Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        {/* Left Side: Reused Dynamic Calculator Component */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-6 sm:p-8 shadow-sm">
            <ToolComponent />
          </div>

          {/* Embed Code Widget Box */}
          <EmbedWidgetBox slug={slug} name={content.name} />

          {/* Under-Calculator Ad banner */}
          <AdBanner
            adCode={process.env.NEXT_PUBLIC_ADSTERRA_BANNER_2 || ''}
            width={300}
            height={250}
          />
        </div>

        {/* Right Side: Sidebar Widgets */}
        <div className="space-y-6">
          <ShareButtons />

          <div className="hidden lg:block">
            <AdBanner
              adCode={process.env.NEXT_PUBLIC_ADSTERRA_BANNER_3 || ''}
              width={160}
              height={600}
            />
          </div>
        </div>
      </div>

      {/* Structured SEO Text Sections */}
      <div className="mt-12 max-w-4xl space-y-10">
        {/* How to Use Section */}
        {content.seoHowToUse && (
          <section className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-6 sm:p-8 shadow-sm">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
              {t(common, 'tool.howToUse')} — {content.name}
            </h2>
            <div className="text-xs sm:text-sm leading-relaxed text-slate-600 dark:text-blue-200/70 whitespace-pre-line">
              {content.seoHowToUse}
            </div>
          </section>
        )}

        {/* Formula / How It Works Section */}
        {content.seoHowItWorks && (
          <section className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-6 sm:p-8 shadow-sm space-y-5">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">
              {t(common, 'tool.howItWorks')} — {content.name}
            </h2>
            <p className="text-xs sm:text-sm leading-relaxed text-slate-600 dark:text-blue-200/70">
              {content.seoHowItWorks}
            </p>
            {content.formula && (
              <div className="bg-gray-50 dark:bg-gray-800/40 p-4 rounded-xl border border-gray-150 dark:border-gray-800 font-mono text-[11px] break-words text-gray-600 dark:text-gray-300">
                <span className="text-xs font-bold text-gray-400 dark:text-gray-500 block mb-2 uppercase tracking-wider">
                  {t(common, 'tool.formula')}:
                </span>
                {content.formula}
              </div>
            )}
            {content.seoExample && (
              <div className="bg-blue-50/20 dark:bg-blue-950/10 border border-blue-100/30 dark:border-blue-900/20 p-5 rounded-xl">
                <span className="text-xs font-bold text-blue-600 dark:text-blue-400 block mb-2 uppercase tracking-wider">
                  {t(common, 'tool.example')}:
                </span>
                <p className="text-xs sm:text-sm leading-relaxed text-slate-600 dark:text-blue-200/70">
                  {content.seoExample}
                </p>
              </div>
            )}
          </section>
        )}

        {/* Frequently Asked Questions */}
        {faqsToUse.length > 0 && (
          <section>
            <FAQ faqs={faqsToUse} title={t(common, 'tool.faq')} />
          </section>
        )}

        {/* Related Tools */}
        {masterTool?.relatedSlugs && (
          <section>
            <RelatedTools relatedSlugs={masterTool.relatedSlugs} locale={currentLocale} />
          </section>
        )}
      </div>
    </div>
  );
}
