"""
execution/send_weekly_email.py
==============================
Helix agent — Step 10 email delivery script.
Reads the generated weekly brief from .tmp/weekly_brief.txt, converts it into a beautifully styled HTML email,
and delivers it to REPORT_EMAIL using execution/shared/send_email.py.
"""

import os
import re
import sys
import logging
import datetime
from pathlib import Path
from dotenv import load_dotenv

# Ensure helix-agent root is in sys.path
BASE_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(BASE_DIR))

from execution.shared.send_email import send_email

# Set up logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [send_weekly_email] %(levelname)s: %(message)s")
log = logging.getLogger("send_weekly_email")

# Load environment
load_dotenv(dotenv_path=BASE_DIR / ".env")


def clean_markdown(text: str) -> str:
    """Strips markdown bold, links, headers, and bullet syntax from text."""
    # Convert markdown links [text](url) -> text (url) or text
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", text)
    # Strip bold / italics
    text = re.sub(r"\*\*|\*", "", text)
    # Strip headers #
    text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)
    return text.strip()


def format_brief_html(brief_text: str, week_date: str) -> str:
    """Formats plain-text brief into a modern, responsive HTML email template."""
    brief_text = clean_markdown(brief_text)
    
    sections = {
        "TRAFFIC SUMMARY": "",
        "TOOL HEALTH": "",
        "PERFORMANCE": "",
        "COMPETITOR ALERTS": "",
        "THIS WEEK'S ACTION": "",
    }

    current_sec = None
    lines = brief_text.splitlines()

    for line in lines:
        cleaned = line.strip()
        upper_line = cleaned.upper().replace("**", "").strip(":- #")
        
        if upper_line in sections:
            current_sec = upper_line
        elif current_sec and cleaned:
            if sections[current_sec]:
                sections[current_sec] += "<br>" + cleaned
            else:
                sections[current_sec] = cleaned

    html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f4f6f8; margin: 0; padding: 20px; color: #1a1a1a; }}
  .container {{ max-width: 650px; background: #ffffff; margin: 0 auto; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); border: 1px solid #e1e4e8; }}
  .header {{ background: #0f172a; color: #ffffff; padding: 24px 28px; text-align: left; }}
  .header h1 {{ margin: 0; font-size: 22px; font-weight: 600; letter-spacing: -0.5px; }}
  .header p {{ margin: 6px 0 0 0; color: #94a3b8; font-size: 13px; }}
  .content {{ padding: 28px; }}
  .card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 18px 20px; margin-bottom: 20px; }}
  .card h2 {{ margin-top: 0; margin-bottom: 10px; font-size: 14px; font-weight: 700; color: #334155; text-transform: uppercase; letter-spacing: 0.5px; }}
  .card p {{ margin: 0; font-size: 14px; line-height: 1.6; color: #475569; }}
  .action-card {{ background: #eff6ff; border: 1px solid #bfdbfe; border-left: 5px solid #2563eb; border-radius: 6px; padding: 20px; margin-top: 24px; }}
  .action-card h2 {{ margin-top: 0; margin-bottom: 8px; font-size: 14px; font-weight: 700; color: #1e40af; text-transform: uppercase; letter-spacing: 0.5px; }}
  .action-card p {{ margin: 0; font-size: 15px; font-weight: 600; line-height: 1.5; color: #1e3a8a; }}
  .footer {{ background: #f1f5f9; padding: 16px 28px; font-size: 12px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; }}
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Helix Executive Brief</h1>
      <p>HelloTools.net Autonomous AI Site Agent &bull; Week of {week_date}</p>
    </div>
    <div class="content">

      <div class="card">
        <h2>📊 Traffic Summary</h2>
        <p>{sections['TRAFFIC SUMMARY'] or 'No significant traffic changes recorded.'}</p>
      </div>

      <div class="card">
        <h2>🛠️ Tool Health</h2>
        <p>{sections['TOOL HEALTH'] or 'All tools operational.'}</p>
      </div>

      <div class="card">
        <h2>⚡ Performance & Core Web Vitals</h2>
        <p>{sections['PERFORMANCE'] or 'All pages meeting LCP thresholds.'}</p>
      </div>

      <div class="card">
        <h2>🎯 Competitor Alerts</h2>
        <p>{sections['COMPETITOR ALERTS'] or 'No new competitor gap alerts.'}</p>
      </div>

      <div class="action-card">
        <h2>🚀 THIS WEEK'S SINGLE ACTION</h2>
        <p>{sections["THIS WEEK'S ACTION"] or 'Continue monitoring traffic & indexation.'}</p>
      </div>

    </div>
    <div class="footer">
      Automated report generated by <strong>Helix Agent</strong> &bull; Sent to {os.getenv('REPORT_EMAIL', 'jdcr518@gmail.com')}
    </div>
  </div>
</body>
</html>"""
    return html_content


def send_weekly_brief_email() -> bool:
    """Reads .tmp/weekly_brief.txt and sends the formatted Monday brief email."""
    log.info("Starting send_weekly_email...")
    
    brief_file = BASE_DIR / ".tmp" / "weekly_brief.txt"
    if brief_file.exists():
        brief_text = brief_file.read_text(encoding="utf-8")
    else:
        log.warning("weekly_brief.txt not found. Using default brief text.")
        brief_text = "TRAFFIC SUMMARY\nSandbox period\n\nTOOL HEALTH\nAll 67 tools passing\n\nPERFORMANCE\nNormal\n\nCOMPETITOR ALERTS\nNone\n\nTHIS WEEK'S ACTION\nApprove pending meta titles."

    today = datetime.date.today()
    monday = today - datetime.timedelta(days=today.weekday())
    week_str = monday.strftime("%b %d, %Y")

    subject = f"Helix Weekly Brief — HelloTools.net [{week_str}]"
    html_body = format_brief_html(brief_text, week_str)
    to_email = os.getenv("REPORT_EMAIL", "jdcr518@gmail.com")

    log.info("Sending Monday brief email to %s...", to_email)
    success = send_email(subject=subject, html_body=html_body, text_body=brief_text)

    if success:
        log.info("Monday brief email delivered successfully to %s!", to_email)
    else:
        log.error("Failed to deliver Monday brief email.")

    return success


if __name__ == "__main__":
    send_weekly_brief_email()
